name: memcache
version: 0.3.0+1
author: Dart Team <misc@dartlang.org>
description: Dart memcache APIs
homepage: https://github.com/dart-lang/memcache
environment:
  sdk: ">=2.0.0-dev.20.0 <3.0.0"
dev_dependencies:
  test: ^1.0.0
